module.exports = {
  TOKEN: process.env.TOKEN || '',
  SET_ROUTE: 'SET_ROUTE',
  USER_LAST_ROUTE: 'USER_LAST_ROUTE',
  READY_FIND_ROUTE: 'READY_FIND_ROUTE',
  EDIT_ROUTE: 'EDIT_ROUTE',
  EDIT_ROUTE_WITH: 'EDIT_ROUTE_WITH',
  EDIT_ROUTE_WITH_EDIT: 'EDIT_ROUTE_WITH_EDIT',
  SELECT_ROUTE: 'SELECT_ROUTE',
  SET_DATE: 'SET_DATE'
}
